### ISSUE TITLE
Java buildbox : move to adoptopenjdk instead of openjdk

### ISSUE THREAD

**Issue by saugereau** [ekino/docker-buildbox#169]
Because openjdk docker image doesn't contains latest fix (https://mail.openjdk.java.net/pipermail/jdk8u-dev/2019-May/009330.html), we should move to adoptopenjdk images . ...

**Comment by Crow-EH** [comment]
Hey @saugereau !

I agree with you, we should move to adoptopenjdk images.
Turns out they now have [an official / verified Docker Hub repository](https://hub.docker.com/_/adoptopenjdk) too, so we should definitely use it instead of the old community ones.

There's just a tiny caveat : the official image doesn't support JDK 10 (since it wasn't supported anymore at its creation) and I wouldn't want to support it on the side like we do for JDK 6.

Should we stop supporting it ? It won't delete the old image of course.

What do you think @sleclercq @fpavageau ?

**Comment by fpavageau** [comment]
I think we can drop JDK 10:
- it's not supported anymore
- once you're already there, upgrading to JDK 11 is not usually an issue

**Comment by Crow-EH** [comment]
I've done some tests & researchs while migrating the java buildboxes.

The community regular images are the same ones than the "official" (verified by Docker), but are released ~1day or more before.

The official repository only has the full images (on Ubuntu), while the community ones also have Ubuntu and Debian "slim" ones (on regular images, not slim, but  slimmed by Adopt and with a "slim java" installed).

Here are some numbers after building our buildboxes with every versions :
- JDK 8:
  - Old java8 (Debian Slim): 784MB
  - Adopt official java8 (Ubuntu): 867MB
  - Adopt community java8 Ubuntu slim: 749MB
  - Adopt community java11 Debian slim: 718MB
- JDK 11:
  - Old java11 (Debian Slim): 899MB
  - Adopt official java11 (Ubuntu): 983MB
  - Adopt community java11 Ubuntu slim: 905MB
  - Adopt community java11 Debian slim: 875MB

Call me a cheapskate, but 100M is 100M. 😅
I'd prefer to use the  `debian-slim` version if everyone is OK with it.
WDYT @saugereau @fpavageau @sleclercq ?

Bonus point: Adopt already removed most of the useless stuff like javafx for jdk8 (+ the `src.zip` for the slim images), so the Dockerfile will be a bit simpler. 👌

PR comming soon ! 🔥

**Comment by Crow-EH** [comment]
By the way, since I didn't use the official images: We could still support JDK 10.
If just forgot to un-un-support it after switching to community...
Cleaning our stuff isn't bad anyway I guess. 🤷‍♀
