### ISSUE TITLE
Java images : move to the new adoptopenjdk repo

### ISSUE THREAD

**Issue by clemstoquart** [ekino/docker-buildbox#190]
Hi,

Currently our java images are based on images from https://hub.docker.com/u/adoptopenjdk which doesn't seem to be the official repo anymore.

We should use base images from https://hub.docker.com/_/adoptopenjdk instead.

**Comment by Crow-EH** [comment]
Hi @clemstoquart.

The official docker repository already existed when we switched to adopt.
The "unofficial" are from the same codebase and maintained on the same repository, just not validated by Docker themselves.

There are various reasons that made me choose these instead of the official, mainly the slim version.

It was just an isolated decision so we can obviously discuss it here and maybe switch to the official image.

Here is a link to the original issue with more details : https://github.com/ekino/docker-buildbox/issues/169#issuecomment-503336330

What do you think ?

**Comment by clemstoquart** [comment]
Hello @Crow-EH 

I didn't know there were already had a discussion about that.

**Comment by Crow-EH** [comment]
It's still a possibility though.
The best would be to have slim images on the official repository. I don't know if it's in their roadmap yet, but at least I know that they won't deprecate the slim community images : https://github.com/AdoptOpenJDK/openjdk-docker/issues/185
