### ISSUE TITLE
Clean java images

### ISSUE THREAD

**Issue by clemstoquart** [ekino/docker-buildbox#501]
Over the years we added a lot of configurations and binaries to the java images. Some of them look outdated or useless:
- ~~`ENV DEBIAN_FRONTEND=noninteractive LANG=C.UTF-8` is in the base image~~
- [ ] CI Helper ?
- [ ] Modd
- [ ] Maven considering almost all projects use Gradle (or the Maven wrapper)
- [ ] `curl -sSL https://salsa.debian.org/debian/mime-support/raw/master/mime.types -o /etc/mime.types` I've no idea why it's here

What do you think ?

**Comment by Crow-EH** [comment]
IMO, this should be done at the same time than #500, so I'll assume wr'll be switching to ubuntu

* `ENV DEBIAN_FRONTEND=noninteractive` exists to force non-interactivity during install commands, like apt, and is common even on Ubuntu. [The good practice should be to set it as an ARG though](ARG DEBIAN_FRONTEND=noninteractive) (by just replacing ENV with ARG).
* `ENV LANG=C.UTF-8` changes the locale to "computer" english which is (marginally) more stable and useable, again a common install thing. It could be something different like POSIX, we'll need to check the available locales on ubuntu with `locale -a`
* CI Helper : [Idk, is GitLab CI's cache great yet](https://github.com/ekino/docker-buildbox/issues/269#issuecomment-601115947) 😄 ?  We could have @rande's input on the question since he made the tool.
*  Modd : OK, definitely should be installed per project if needed
* Maven : OK, now that the wrapper is common it should be like Graddle
* `curl -sSL https://salsa.debian.org/debian/mime-support/raw/master/mime.types -o /etc/mime.types` : [An old fix for missing mime types, used by aws cli when uploading on S3 for its metadata](https://github.com/ekino/docker-buildbox/pull/117). It may be useless on Debian now, [and is useless on ubuntu because the package is up to date.](https://packages.ubuntu.com/focal/mime-support)

**Comment by clemstoquart** [comment]
> IMO, this should be done at the same time than #500, so I'll assume we'll be switching to ubuntu
> 
>     * `ENV DEBIAN_FRONTEND=noninteractive` exists to force non-interactivity during install commands, like apt, and is common even on Ubuntu. [The good practice should be to set it as an ARG though](https://github.com/moby/moby/issues/4032) (by just replacing ENV with ARG).
> 
>     * `ENV LANG=C.UTF-8` changes the locale to "computer" english which is (marginally) more stable and useable, again a common install thing. It could be something different like POSIX, we'll need to check the available locales on ubuntu with `locale -a`
> 

My point is that these 2 env variables are setted in the base image and inherited. So to me it's just a duplicated piece of code.

**Comment by Crow-EH** [comment]
By the way, here are the available locales on eclipse-temurin :
```
# locale -a
C
C.UTF-8
en_US.utf8
POSIX
```

**Comment by clemstoquart** [comment]
You're right it's not the same.

**Comment by Crow-EH** [comment]
@clemstoquart I think we need to keep [CI Helper](https://github.com/rande/gitlab-ci-helper) for now, some points in [@saugereau's comment from 2020](https://github.com/ekino/docker-buildbox/issues/269#issuecomment-601115947) are still valid, like [multiple artifacts still not being supported](https://gitlab.com/gitlab-org/gitlab/-/issues/18744).

I think we'll remove CI Helper from all images in one go when it's time.

**Comment by clemstoquart** [comment]
@Crow-EH Well I'm sure CI Helper has useful features but does at least one java project used it ?

**Comment by clemstoquart** [comment]
First step : https://github.com/ekino/docker-buildbox/pull/543
